@echo off
echo Starting Catalog AI Application...
echo.
echo Starting backend server...
start "Backend Server" cmd /k "cd backend && call venv\Scripts\activate && python app.py"
echo.
echo Waiting 5 seconds for backend to start...
timeout /t 5 /nobreak > nul
echo.
echo Starting frontend development server...
start "Frontend Server" cmd /k "cd frontend && npm start"
echo.
echo Both servers are starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000
echo.
echo Press any key to exit this window...
pause > nul
